---
- name: Run Terraform
  hosts: localhost
  vars:
    project_dir: /home/daniel/Repos/infra/terraform
  environment:
    # PM_API_TOKEN_ID: terraform-prov@pve!terraform-provisioner
    # PM_API_TOKEN_SECRET: c606811f-789f-4c4d-a7a4-50ad72ac284b
  tasks:
    # - name: Install necessary components to support infra
    #   shell:
    #     cmd: "terraform init"
    #     chdir: ../terraform
    #   when: terraform.tfstate not present
    - name: Run terraform
      terraform:
        project_path: "{{ project_dir }}"
        state: present
    # - name: Configure all clients
    #   vars:
    #     targets: containers
