---

- name: Setup Docker if not present/running
  block:
  - name: Check if Docker is running
    command: systemctl status docker
    changed_when: false

  rescue:
  - name: Setup calling with a default user
    vars:
      docker_user: "{{ docker_user }}"
      groupname: "{{ groupname }}"
    import_tasks: roles/common/tasks/setup-user-group.yaml

  - name: Setup Docker in calling container
    import_tasks: roles/common/tasks/setup-docker-support.yaml

  always:
  - name: Copy docker-compose.yaml
    copy:
      src: docker-compose.yaml
      dest: "{{ docker_compose_dir }}"
      owner: "{{ docker_user }}"
      group: "{{ groupname }}"
      mode: 0644

  - name: Deploy docker applications
    become: true
    become_user: "{{ docker_user }}"
    become_method: su
    community.docker.docker_compose:
      project_src: "{{ docker_compose_dir }}"
      state: present
