---

- name: Download 1password-cli
  vars:
    gpg_fp: AA16FCBCA621E701
  tags:
    - 1password
  become: true
  block:
  # Note: the name of the resulting file matters! Must use the same name as provided by package!
  - name: Trust 1password gpg key
    get_url:
      url: https://downloads.1password.com/linux/keys/1password.asc
      dest: /usr/share/keyrings/1password-archive-keyring.asc
      mode: 0644

  # TODO: Dependent on being x86_64, 1password has binaries for ARM as well, but {{ ansible_architecture }} only gives x86_64 and not amd64
  - name: Add 1password repo
    apt_repository:
      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.asc] https://downloads.1password.com/linux/debian/amd64 stable main
      filename: 1password
      state: present
    when: ansible_architecture == "x86_64"

  - name: Create 1password policy folder for debsig
    file:
      state: directory
      path: "/etc/debsig/policies/{{ gpg_fp }}"
      mode: '0600'

  - name: Download policy
    get_url:
      url: https://downloads.1password.com/linux/debian/debsig/1password.pol
      dest: "/etc/debsig/policies/{{ gpg_fp }}/1password.pol"

  - name: Create 1password policy for dpkg-sig
    file:
      state: directory
      path: "/usr/share/debsig/keyrings/{{ gpg_fp }}"
      mode: '0600'

  - name: Download policy
    get_url:
      url: https://downloads.1password.com/linux/keys/1password.asc
      dest: "/usr/share/debsig/keyrings/{{ gpg_fp }}/debsig.gpg"

  - name: Install cli tool and app
    apt:
      name:
        - 1password-cli
      update_cache: true

  # For some reason there is an extra line added to the sources list when this is run, so we need to remove it
  # TODO: Would be nice to make all magic names and paths parameterized here.
  - name: Remove duplicated source list line
    lineinfile:
      path: /etc/apt/sources.list.d/1password.list
      line: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
      state: absent
