---

# By delegating this, the execution is performed where it is supposed to,
# but the fact (vmid) will be available in the $inventory_host CT, i.e. calling CT,
# as long as delegate_facts = False (default); with True, the delegate will have the fact locally instead
- name: Perform setup
  tags:
    - never
    - setup
  block:
    - name: Setup for containers
      tags:
        - container
      block:
      - name: Get the VMID for this container
        import_tasks: container-setup.yaml

      # TODO: This actually does not alter existing CTs, but can only spawn new with correct permissions. Find replacement!
      # - name: Setup host os to support docker in lxc
      #   tags:
      #     - docker
      #   import_tasks: enable-keyctl-for-ct.yaml
      #   delegate_to: pve
      #   delegate_facts: true
