---
# Taken from https://gist.github.com/JSinghDev/10e0824580a84a56022153592ac64faa
- name: Get mountpoint for zfs_dataset
  import_tasks: get-zfs-mountpoint.yaml
- name: Make group name globally available (in file?)
  set_fact:
    groupname: container-data
# Groups in LXCs are normally prefixed with "10" before real group number
- name: Create group used for (unprivileged) containers to access data
  group:
    name: "{{ groupname }}"
    gid: 101000
    state: present
- name: Install ACLs
  apt:
    name: acl
- name: Make sure that ZFS uses posix acls
  zfs:
    name: "{{ zfs_dataset }}"
    state: present
    extra_zfs_properties:
      acltype: posixacl
  register: output
  # changed_when: output.stdout != ""
- name: Set group permissions and mod for the share
  file:
    path: "{{ shared_filesystem }}"
    recurse: yes
    group: "{{ groupname }}"
    # mode: '2775'
- name: Set default ACL permissions for {{ groupname }}
  acl:
    path: "{{ shared_filesystem }}"
    recursive: yes
    entity: "{{ groupname }}"
    etype: group
    permissions: rwx
    default: yes
    state: present
- name: Set ACL permissions for {{ groupname }} for current files
  acl:
    path: "{{ shared_filesystem }}"
    recursive: yes
    entity: "{{ groupname }}"
    etype: group
    permissions: rwx
    state: present
- name: Mount data storage
  shell:
    cmd: pct set {{ current_vmid }} -mp0 {{ shared_filesystem }},mp={{ mountpoint }}
