---
# - hosts: pve
#   vars:
#     system_under_config: media
#   tasks:
#     - name: Add prerequisites for running Proxmox plugin
#       pip:
#         name:
#           - proxmoxer
#           - requests
#     - name: "Enable keyctl feature in: {{ system_under_config }}"
#       community.general.proxmox:
#         # vmid: "{{ current_vmid }}"
#         vmid: 100
#         api_user: root@pam
#         api_password: ***REMOVED***
#         api_host: 192.168.1.101
#         features:
#           - nesting=1
#           - keyctl=1
#         state: started
#   # This needs to be done here, as root, since the Terraform (or any other) user is not allowed to perform this change

# Partly taken from https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
# - name: Add requirement for docker to run (?)
#   hosts: media
#   vars:
#     system_under_config: "{{ hostvars['pve']['system_under_config'] }}"
#   tasks:
- name: Add docker
  tags: docker
  block:
    - name: Install Docker prerequisites
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Get DEB architecture # for when adding repo in next step
      shell: dpkg --print-architecture
      register: deb_architecture
      changed_when: deb_architecture.stdout != "amd64"
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        pkg:
          - docker-ce
          - docker-compose
        state: latest
        update_cache: true

    - name: Install Docker (and other deps) Module for Python
      pip:
        name:
          - docker
          - pyyaml
      notify:
        - Start Docker