---
system_under_config: "{{ inventory_hostname }}"

mounts:
  configs:
    zfs_dataset: Tank2/appdata
    ct_mountpoint: "/storage/appdata"
  cloud:
    zfs_dataset: Tank3/cloud
    ct_mountpoint: "/storage/cloud"

docker_compose_dir: "/home/default-user"
backup_user: "default-user"

# The autorestic setup is taken directly from:
# https://0xacab.org/varac-projects/ansible-role-autorestic

restic_backup_locations:
  - name: cloud
    from: /storage/cloud
    to: b2
  # - name: libs
  #   from: /var/lib
  #   forget: prune
  #   hooks:
  #     success:
  #       # Export metrics for prometheus node-exporter textfile-collector
  #       # Needs "sponge" binary from i.e. "moreutils" debian package
  #       - /usr/local/bin/autorestic-metrics.sh | sponge /var/lib/prometheus/node-exporter/autorestic.prom

restic_all_backends:
  # s3-storage:
  #   type: s3
  #   # create one bucket per host
  #   path: "s3.amazonaws.com/{{ restic_backup_host_prefix }}"
  b2:
    type: b2
    path: 'edholm-cloud-backup'
# Keys for Backblaze
autorestic_additional_env:
  B2_ACCOUNT_ID: "0007639dc9314de000000000c"
  B2_ACCOUNT_KEY: "K00000IYuGCc8SYz+3w2ALjoZdZljNY"

restic_enabled_backends:
  - b2
