---

- include_tasks: ./github-download.yaml
  vars:
    release:
      name: restic
      repo: "restic/restic"

- include_tasks: ./github-download.yaml
  vars:
    release:
      name: autorestic
      repo: "cupcakearmy/autorestic"

- name: Ensure {{ autorestic_dir }} dir
  ansible.builtin.file:
    path: "{{ autorestic_dir }}"
    state: directory
    mode: '0700'

# TODO: The current implementation keps giving a broken yaml file with wrong indentation.
#       While a generic solution 
# - name: Deploy autorestic.yaml configuration to {{ autorestic_dir }}/{{ autorestic_config_filename }}
#   become: true
#   become_user: "{{ backup_user }}"
#   become_method: su
#   when: restic_backup_locations|length > 0
#   ansible.builtin.template:
#     src: autorestic.yaml.j2
#     dest: "{{ autorestic_dir }}/{{ autorestic_config_filename }}"
#     mode: 0600

- name: Deploy autorestic.yaml configuration to {{ autorestic_dir }}/{{ autorestic_config_filename }}
  become: true
  become_user: "{{ backup_user }}"
  become_method: su
  when: restic_backup_locations|length > 0
  ansible.builtin.copy:
    src: autorestic.yaml
    dest: "{{ autorestic_dir }}/{{ autorestic_config_filename }}"
    mode: 0600

- name: Deploy autorestic.env file to {{ autorestic_dir }}/{{ autorestic_env_filename }}
  when: restic_backup_locations|length > 0
  become: true
  become_user: "{{ backup_user }}"
  become_method: su
  ansible.builtin.template:
    src: autorestic.env.j2
    dest: "{{ autorestic_dir }}/{{ autorestic_env_filename }}"
    mode: 0600

- name: Ensure systemd user dir exists
  become: true
  become_user: "{{ backup_user }}"
  become_method: su
  file:
    path: "/home/{{ backup_user }}/.config/systemd/user"
    state: directory
    mode: 0744

- name: Deploy autorestic service unit
  when: restic_backup_locations|length > 0
  become: true
  become_user: "{{ backup_user }}"
  become_method: su
  ansible.builtin.template:
    src: autorestic.service.j2
    dest: "/home/{{ backup_user }}/.config/systemd/user/autorestic.service"
    mode: 0644

- name: Deploy autorestic timer
  when: restic_backup_locations|length > 0
  become: true
  become_user: "{{ backup_user }}"
  become_method: su
  ansible.builtin.template:
    src: autorestic.timer.j2
    dest: "/home/{{ backup_user }}/.config/systemd/user/autorestic.timer"
    mode: 0644

# - name: Deploy autorestic-metrics.sh
#   ansible.builtin.copy:
#     src: autorestic-metrics.sh
#     dest: /usr/local/bin/autorestic-metrics.sh
#     mode: 0755

# Beware of [Check and init command ignore YAML options](https://github.com/cupcakearmy/autorestic/issues/198)
- name: Check (and eventually initialize) all restic backends
  when: restic_backup_locations|length > 0
  ansible.builtin.command: autorestic --ci -c "{{ autorestic_dir }}/{{ autorestic_config_filename }}" check

- name: Enable autorestic systemd timer
  tags:
    - systemd
  ansible.builtin.systemd:
    name: autorestic.timer
    daemon_reload: true
    state: started
    scope: user
    enabled: true
    masked: false
