---

# A missing sys/acl.h solved by this; https://man7.org/tlpi/code/faq.html#sys-acl.h-missing
- name: Install borg requirements
  apt:
    pkg: 
    - pip
    - pkg-config
    - libacl1-dev

- name: Install Borgmatic
  become: true
  become_user: "{{ backup_user }}"
  become_method: su
  pip:
    name: borgmatic

# TODO: Specify manual steps for remote repo init
# Ensure ssh pub key, e.g. via 1pass, bw. Either manually, or
# op item get "SSH Key" --fields "public key" > ~/.ssh/id_ed25519.pub
# ssh-copy-id -f -p23 -i ~/.ssh/id_ed25519.pub -s u368673@u368673.your-storagebox.de
# borgmatic init --encryption repokey --config files/cloud-borg-backup.yaml
# Enter a passphrase for the repokey encryption, manually
# borg key export ssh://u368673@u368673.your-storagebox.de:23/./cloud-backup.borg
# THe passphrase alone does not suffice, but the key must also be saved

- name: Ensure systemd user dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: 0744

# TODO: Loop over all borg configs to backup
- name: Setup systemd service and timer for given configuration
  become: true
  become_user: "{{ backup_user }}"
  become_method: su
  block:
  - name: Deploy borgmatic services
    loop:
      - cloud-borg-backup
    loop_control:
      loop_var: borgmatic_config_filename
    include_tasks: systemd-services.yaml
  
