
  - name: "Deploy configuration to {{ borgmatic_config_filename }}"
    ansible.builtin.copy:
      src: "files/{{ borgmatic_config_filename }}.yaml"
      dest: "{{ ansible_env.HOME }}/{{ borgmatic_config_filename }}.yaml"
      mode: 0600

  # TODO: Add notification to <service> if backup does not run
  - name: Deploy borgmatic service unit
    ansible.builtin.template:
      src: borgmatic.service.j2
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ borgmatic_config_filename }}.service"
      mode: 0640

  - name: Deploy borgmatic timer
    ansible.builtin.template:
      src: borgmatic.timer.j2
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ borgmatic_config_filename }}.timer"
      mode: 0640

  - name: Enable autorestic systemd timer
    ansible.builtin.systemd:
      name: "{{ borgmatic_config_filename }}.timer"
      daemon_reload: true
      state: started
      scope: user
      enabled: true
      masked: false