---

version: 2

locations:
  cloud:
    from: /storage/cloud
    to: b2
    options:
      forget:
        keep-daily: 7
        keep-monthly: 3
        keep-weekly: 4

backends:
  b2:
    path: edholm-cloud-backup
    type: b2
    env:
      B2_ACCOUNT_ID: '0007639dc9314de000000000c'
      B2_ACCOUNT_KEY: 'K00000IYuGCc8SYz+3w2ALjoZdZljNY'
