---

# By delegating this, the execution is performed where it is supposed to,
# but the fact (vmid) will be available in the $inventory_host CT, i.e. calling CT,
# as long as delegate_facts = False (default); with True, the delegate will have the fact locally instead
- name: Setup for containers
  tags:
    - container
  block:
  - name: Get the VMID for this container
    import_tasks: roles/common/tasks/find-vmid-from-name.yaml
    when: current_vmid is not defined
    delegate_to: pve

  - name: Mount the given zfs dataset in the calling ct
    # tags: 
    #   - bind_mount
    import_tasks: roles/common/tasks/setup-bind-mount.yaml
    when: mounts is defined
    delegate_to: pve

  # - name: Add TUN device for OpenVPN access
  #   import_tasks: add-tun-tap-device.yaml
  #   delegate_to: pve
