---

- name: Enable Ansible-proxmox plugin, and make possible to run docker in CT
  tags: docker
  block:
    - name: Ensure pip is installed
      apt:
        pkg:
          - python3-pip

    - name: Add prerequisites for running Proxmox plugin
      pip:
        name:
          - proxmoxer
          - requests

    # TODO: The features do not actually change anything at this point,
    #       only used when creating a container
    - name: "Enable keyctl feature for {{ current_vmid }}"
      community.general.proxmox:
        vmid: "{{ current_vmid }}"
        api_user: "{{ lookup('onepassword', 'Proxmox', field='username') }}@pam"
        api_password: "{{ lookup('onepassword', 'Proxmox', field='password') }}"
        api_host: 192.168.1.100
        features:
          - nesting=1
          - keyctl=1   ## TODO: DOES NOT WORK OOB, NEED TO BE FIXED! RESTART CT?
          - fuse=1     ## In order to access ZFS (bind)mounts inside Docker cts 
          - mknod=1
        state: started
      # This needs to be done here, as root, since the Terraform (or any other) user is not allowed to perform this change
