---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Create test user
      ansible.builtin.user:
        name: default-user
        shell: /bin/bash
        create_home: true

  tasks:
    - name: Include borgmatic role
      ansible.builtin.include_role:
        name: borgmatic
      vars:
        borgmatic_test_mode: true
