---

system_under_config: "{{ inventory_hostname }}"

# Dict for every mount we want to have accessible in our CT, where 'zfs_dataset' is 
# the name of the dataset on the host (note that it is not a path!) and moutpoint is
# where the data should be accessible from within the container. 
mounts:
  configs:
    zfs_dataset: Tank2/appdata
    ct_mountpoint: "/appdata"
  downloads:
    zfs_dataset: Tank2
    ct_mountpoint: "/storage/downloads"
  movies:
    zfs_dataset: Tank/windows_smb
    ct_mountpoint: "/storage/movies"
  tv_series:
    zfs_dataset: Tank/windows_smb_series
    ct_mountpoint: "/storage/tv_series"
  media:
    zfs_dataset: Tank/windows_smb_util
    ct_mountpoint: "/storage/media"

docker_compose_dir: "/home/default-user"
