---

version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=1000
      - TZ=Europe/Stockholm
      - CLI_ARGS= #optional
    volumes:
      - /root/duplicati_config:/config
      #- </path/to/backups>:/backups
      - /storage/cloud:/source
    ports:
      - 8200:8200
    restart: unless-stopped