- name: Restart docker apps
  community.docker.docker_compose_v2:
    project_src: /opt/docker
    remove_orphans: true
    state: present

# daemon.json is only read at daemon start.
- name: Restart docker daemon
  become: true
  service:
    name: docker
    state: restarted
