---

autorestic_service_dir: "{{ ansible_env.HOME }}/.config/systemd/user"
autorestic_dir: /storage/appdata/autorestic
autorestic_config_filename: .autorestic.yml
autorestic_env_filename: .autorestic.env

restic_default_options:
  forget:
    keep-daily: 7
    keep-weekly: 4
    keep-monthly: 3

restic_default_snapshot_policy:
  daily: 7
  weekly: 4
  monthly: 3

restic_backup_locations: []

# systemd time OnCalendar
# see https://www.freedesktop.org/software/systemd/man/systemd.time.html for
# details
# Default: Daily at 12:30pm local time
autorestic_systemd_timer_backup: "*-*-* 12:30:00"
