---

# Groups and users in LXCs are normally prefixed with "10" before real group number
# Currently the group is called the same in the guest and the host -- maybe that is confusing?
- name: Check required variables
  assert:
    that:
      - docker_user is defined
      - groupname is defined
    fail_msg: "docker_user and groupname must be defined"

- name: Setup a corresponding group in LXC container
  group:
    name: "{{ groupname }}"
    gid: 1000
    state: present

- name: Create default user, add to correct groups
  become: true
  user:
    name: "{{ docker_user }}"
    create_home: true
    uid: 1000
    group: "{{ groupname }}"
    shell: /usr/bin/fish
    password: "{{ lookup('onepassword', 'infra_default_user') | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string)}}"
    groups: sudo
    append: true

- name: "Ensure {{ docker_user }} .ssh dir"
  file:
    path: "/home/{{ docker_user }}/.ssh"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ groupname }}"
    mode: "0700"

- name: Copy authorized_keys to user
  become: true
  copy:
    src: /root/.ssh/authorized_keys
    remote_src: true
    dest: "/home/{{ docker_user }}/.ssh/authorized_keys"
    owner: "{{ docker_user }}"
    group: "{{ groupname }}"
    mode: '0600'

- name: Add valuable aliases for "{{ docker_user }}"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      alias ll='ls -alF'
      alias la='ls -A'
      alias l='ls -CF'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Aliases"
    create: true
    mode: "0644"

- name: ensure "{{ docker_user }}" is lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ docker_user }}"
  register: docker_user_lingering

- name: enable lingering for "{{ docker_user }}"
  become: true
  ansible.builtin.command: "loginctl enable-linger {{ docker_user }}"
  changed_when: false
  when: not docker_user_lingering.stat.exists

- name: Ensure user local bin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ groupname }}"
    mode: '0755'

- name: Disable SSH root login
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart ssh
