---

- name: Initialize desired mount entries
  set_fact:
    desired_mount_entries: []

- name: Parse mounts from JSON string
  set_fact:
    mounts_list: "{{ mounts | from_json }}"

- name: Gather ZFS mountpoint information
  include_tasks: gather-mount-entry.yaml
  loop: "{{ mounts_list }}"
  loop_control:
    label: "{{ item.dataset }}"

- name: Get current mountpoints from config
  slurp:
    path: "/etc/pve/lxc/{{ current_vmid }}.conf"
  register: lxc_config

- name: Parse current mount entries
  set_fact:
    current_mount_lines: "{{ lxc_config.content | b64decode | regex_findall('^lxc\\.mount\\.entry:.*$', multiline=True) }}"

- name: Determine mount entries to add
  set_fact:
    mounts_to_add: "{{ desired_mount_entries | rejectattr('line', 'in', current_mount_lines) | list }}"

- name: Determine mount entries to remove
  set_fact:
    mounts_to_remove: "{{ current_mount_lines | difference(desired_mount_entries | map(attribute='line') | list) }}"

- name: Add missing mount entries
  lineinfile:
    path: "/etc/pve/lxc/{{ current_vmid }}.conf"
    line: "{{ item.line }}"
    insertafter: "^unprivileged"
  loop: "{{ mounts_to_add }}"
  loop_control:
    label: "{{ item.source }} -> {{ item.target }}"
  notify: Restart container

- name: Remove obsolete mount entries
  lineinfile:
    path: "/etc/pve/lxc/{{ current_vmid }}.conf"
    line: "{{ item }}"
    state: absent
  loop: "{{ mounts_to_remove }}"
  notify: Restart container
