---

- name: Get mountpoint for {{ item.dataset }}
  zfs_facts:
    name: "{{ item.dataset }}"
  register: dataset_facts

- name: Validate and add to mount entries
  set_fact:
    desired_mount_entries: "{{ desired_mount_entries + [entry] }}"
  loop: "{{ dataset_facts.ansible_facts.ansible_zfs_datasets }}"
  loop_control:
    loop_var: dataset
    label: "{{ dataset.name }}"
  vars:
    mountpoint_in_container: "{{ item.path }}"
    entry:
      source: "{{ dataset.mountpoint }}"
      target: "{{ mountpoint_in_container }}"
      line: "lxc.mount.entry: {{ dataset.mountpoint }} {{ mountpoint_in_container[1:] }} none rbind,create=dir,optional 0 0"
  failed_when: >
    dataset.mountpoint is not regex('^/.*') or
    dataset.mounted != "yes"
