---

- name: Get mountpoint for {{ item.value.zfs_dataset }}
  zfs_facts:
    name: "{{ item.value.zfs_dataset }}"
  register: dataset_facts

- name: Print and check mountpoint
  set_fact:
    shared_filesystems: "{{ shared_filesystems + [ dataset.mountpoint ] }}" 
  loop: "{{ dataset_facts.ansible_facts.ansible_zfs_datasets }}"
  loop_control:
    label: "{{ [dataset.mountpoint, dataset.mounted] }}"
    loop_var: dataset
  # TODO: Very naive path check, fix?
  failed_when: >
    dataset.mountpoint is not regex('^/.*') or 
    dataset.mounted != "yes"
