- name: Generate docker-compose files for selected apps
  block:
    - name: Check for additional tasks file
      stat:
        path: "{{ role_path }}/tasks/additional/{{ item }}.yml"
      register: additional_tasks_check
      loop: "{{ docker_apps }}"

    - name: Execute pre-deployment tasks
      include_tasks: "{{ role_path }}/tasks/additional/{{ item.item }}.yml"
      vars:
        task_phase: "pre"
      when: 
        - item.stat.exists
        - additional_tasks_pre is defined
      loop: "{{ additional_tasks_check.results }}"
      loop_control:
        loop_var: item

    - name: Generate docker-compose files
      template:
        src: "{{ item }}.yml.j2"
        dest: "/opt/docker/{{ item }}.yml"
      loop: "{{ docker_apps }}"

    - name: Execute post-deployment tasks
      include_tasks: "{{ role_path }}/tasks/additional/{{ item.item }}.yml"
      vars:
        task_phase: "post"
      when: 
        - item.stat.exists
        - additional_tasks_post is defined
      loop: "{{ additional_tasks_check.results }}"
      loop_control:
        loop_var: item

  notify: Restart docker apps
