---
- name: Install all basic packages needed for the host
  hosts: pve
  tasks:
    - name: Install pip
      apt:
        name: python3-pip

- name: Add requirement for docker to run (?)
  hosts: "{{ system_under_config }}"
  tasks:
    - name: Install required jsondiff for docker stack
      pip:
        name: jsondiff