---

# - hosts: pve
#   tasks:
#     - include_role:
#         name: Base setup of host
#         tasks_from: setup-bind-mount

- hosts: media
  # pre_tasks:
  #   - name: Make sure that that necessary variables are set
  #     fail:
  #       msg: You need to pass the variable zfs_dataset, with a valid ZFS dataset
  #     when: zfs_dataset is not defined
  roles:
    - role: common
    - role: media

- hosts: backup
  roles:
    - role: common
    - role: backup

- hosts: network
  vars_files:
    - secrets.yaml
  roles:
    - role: common
    - role: network

- hosts: collaboration
  vars_files:
    - secrets.yaml
  roles:
    - role: common
    - role: collaboration

- hosts: fileSharing
  vars_files:
    - secrets.yaml
  roles:
    - role: fileSharing
