---
- name: Playbook for installing terraform on proxmox hypervisor
  hosts: localhost
  remote_user: root
  tasks:
    - name: Install necessary packages for adding new repositories
      apt:
        name: software-properties-common
        state: present
    - name: Add Terraform/Hashicorp's signing key to apt
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Get DEB architecture (for when adding repo in next step)
      shell: dpkg --print-architecture
      register: deb_architecture
      changed_when: deb_architecture.stdout != "amd64"
    - name: Add terraform repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
    - name: Install terraform from hashicorp repo
      apt:
        name: terraform
        state: present
        update_cache: yes
    # NOTE: Terraform will by itself go and fetch the Proxmox integration (provider) from Github and install it. No need for it here

- name: Add terraform user in proxmox host, with VM permissions
  hosts: pve # TODO: Should not require that a semi-static inventory/hosts list is defined
  remote_user: root
  tasks:
    - name: Create a new role, TerraformProv, for the future terraform user
      command: pveum role add TerraformProv -privs "VM.Allocate VM.Clone VM.Config.CDROM VM.Config.CPU VM.Config.Cloudinit VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Monitor VM.Audit VM.PowerMgmt Datastore.AllocateSpace Datastore.Audit"
    - name: Create a 'terraform-prov' user
      command: pveum user add terraform@pve --comment "User for terraform usage only"
    - name: Add the TerraformProv role to the terraform-prov user
      command: pveum aclmod / -user terraform-prov@pve -role TerraformProv
    - name: Edit permissions to enable creation of VMs, CTs
      command:
        cmd: pveum user token add terraform-prov@pve terraform-provisioner --privsep 0
        register: table-with-token
      # TODO: Add some kind of regex to get the token secret here
    # - name: Check that the new user is created
    #   proxmox_user_info: # Could use to check if normal "ansible-command pveum..." was successful?
    #     api_host: proxmox
    #     api_user: root
