---
version: '3.5'

# Taken from https://stackoverflow.com/a/48651071, available since 3.4
x-common-env: &common-environment
  PUID: 1000
  PGID: 1000
  UMASK_SET: 022
  TZ: Europe/Stockholm
services:
######## MEDIA ACQUISITION ########
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    ports:
      - "9696:9696"
    environment: *common-environment
    volumes: 
      - /storage/appdata/prowlarr:/config
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      <<: *common-environment
      TRANSMISSION_WEB_HOME: /flood-for-transmission/ #optional
      USER: yarcod #optional
      PASS: aeyfe!2874Tra #optional
    volumes:
      - /storage/appdata/transmission:/config
      - /storage/downloads:/media
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment: *common-environment
    volumes:
      - /storage/appdata/radarr:/config
      - /storage/movies:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment: *common-environment
    volumes:
      - /storage/appdata/sonarr:/config
      - /storage/tv_series/:/media
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    ports:
      - "8686:8686"
    environment: *common-environment
    volumes:
      - /storage/appdata/lidarr:/config
      - /storage/media/:/media
    restart: unless-stopped

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    ports:
      - "5299:5299"
    environment:
      <<: *common-environment
      DOCKER_MODS: linuxserver/mods:universal-calibre #optional
    volumes:
      - /storage/appdata/lazylibrarian:/config
      - /storage/media/:/media
    restart: unless-stopped

######## MEDIA HANDLING ########
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      <<: *common-environment
      JELLYFIN_PublishedServerUrl: 192.168.1.101 #optional
      # TODO: Make compose file a template and replace ip with host ip var
    volumes:
      - /storage/appdata/jellyfin:/config
      - /storage/tv_series:/media/tvshows
      - /storage/movies:/media/movies
    ports:
      - 8096:8096 # Http webUI
      - 8920:8920 # Https webUI (optional)
      - 7359:7359/udp # Clients discovery of Jellyfin on LAN (optional)
      # - 1900:1900/udp # Service discovery by DLNA/-clients (optional)
    restart: unless-stopped

# When setting up this application (v1.1.1) and you enter setup with Jellyfin account
# make sure that the hostname ends with a '/' to indicate that there is no subfolder
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      <<: *common-environment
      LOG_LEVEL: debug
    ports:
      - 5055:5055
    volumes:
      - /storage/appdata/jellyseerr:/app/config
    restart: unless-stopped

## TODO: There will need to be a "network" part here with vlan tagging, e.g. from
# https://en-designetwork.daichi703n.com/entry/2018/05/02/docker-compose-network-vlan-tag
# networks:
#   vlan20:
#     name: vlan20
#     driver: macvlan
#     driver_opts:
#       parent: ens192.20
#     ipam:
#       config:
#         - subnet: 192.168.20.0/24
#           gateway: 192.168.20.1