---
version: '3'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn
    volumes:
      - /storage/media/downloads:/media/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=WINDSCRIBE
      - OPENVPN_CONFIG=Copenhagen-LEGO-tcp
      - OPENVPN_USERNAME=yarcod_2swrehp59
      - OPENVPN_PASSWORD=9n75rf4b8q
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24 # Enables access from local net despite VPN being active. Could use rev. proxy also/instead
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_WEB_UI=combustion
      - DNS=9.9.9.9,1.1.1.1
    cap_add:
      - NET_ADMIN
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: 10m
    ports:
      - 9091:9091
      - 9117:9117
      - 7878:7878
      - 8989:8989
      - 8686:8686
      - 5299:5299
      - 9696:9696 # Prowlarr
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    network_mode: "service:transmission-openvpn"
    container_name: prowlarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Stockholm
    volumes:
        - /storage/appdata/prowlarr:/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    network_mode: "service:transmission-openvpn"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=022 #optional
    volumes:
      - /storage/appdata/radarr:/config
      - /storage/media:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    network_mode: "service:transmission-openvpn"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=022 #optional
    volumes:
      - /storage/appdata/sonarr:/config
      - /storage/media/:/media
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    network_mode: "service:transmission-openvpn"
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=022 #optional
    volumes:
      - /storage/appdata/lidarr:/config
      - /storage/media/:/media
    restart: unless-stopped

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian
    network_mode: "service:transmission-openvpn"
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - /storage/appdata/lazylibrarian:/config
      - /storage/media/:/media
    restart: unless-stopped