---
version: '3'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    user: "1000:1000"
    ports:
      - "9696:9696"
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Stockholm
    volumes:
        - /storage/appdata/prowlarr:/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    user: "1000:1000"
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=022 #optional
    volumes:
      - /storage/appdata/radarr:/config
      - /storage/media:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    user: "1000:1000"
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=022 #optional
    volumes:
      - /storage/appdata/sonarr:/config
      - /storage/media/:/media
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    user: "1000:1000"
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=022 #optional
    volumes:
      - /storage/appdata/lidarr:/config
      - /storage/media/:/media
    restart: unless-stopped

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    user: "1000:1000"
    ports:
      - "5299:5299"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - /storage/appdata/lazylibrarian:/config
      - /storage/media/:/media
    restart: unless-stopped

## TODO: There will need to be a "network" part here with vlan tagging, e.g. from
# https://en-designetwork.daichi703n.com/entry/2018/05/02/docker-compose-network-vlan-tag
# networks:
#   vlan20:
#     name: vlan20
#     driver: macvlan
#     driver_opts:
#       parent: ens192.20
#     ipam:
#       config:
#         - subnet: 192.168.20.0/24
#           gateway: 192.168.20.1