---

- name: Install Samba
  become: true
  package:
    name:
      - acl
      - cockpit
      - python3-pexpect
      - samba
    state: present

- name: Ensure smbusers group exists
  become: true
  group:
    name: smbusers
    state: present

# - name: Ensure shared directory
#   file:
#     path: /storage/cloud
#     state: directory
#     owner: "{{ share_user }}"
#     group: smbusers
#     mode: "2775"

# - name: Set default ACL for shared directory
#   acl:
#     path: /storage/cloud
#     default: true
#     entity: smbusers
#     etype: group
#     permissions: rwx
#     state: present

- name: Add Samba configuration
  become: true
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [{{ item.name }}]
      path = {{ item.path }}
      read only = no
      browsable = yes
      guest ok = no
      valid users = @smbusers
      create mask = 0660
      directory mask = 0770
      vfs objects = acl_xattr
      map acl inherit = yes
      store dos attributes = yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Samba Share"
  loop: "{{ (mounts | default('[]') | from_json) }}"
  notify: Restart Samba

- name: Create Samba users and set passwords
  include_tasks: smb-user.yaml
  vars:
    samba_user: "{{ item }}"
  loop: "{{ samba_users }}"

- name: Add cockpit extensions
  ansible.builtin.include_tasks:
    file: playbooks/github-download.yaml
  vars:
    release:
      name: cockpit-file-sharing
      repo: 45Drives/cockpit-file-sharing

- name: Enable and start Samba service
  systemd:
    name: smbd
    enabled: true
    state: started
