# ---
# # LXC Container setup
# container_user: "container-data"

# # Docker setup
# docker_user: "default-user"
# docker_release:
# docker_release_shasum:
groupname: container-data
docker_user: default-user
