---

- name: Setup Docker if not present/running
  block:
    - name: Check if Docker is running
      command: systemctl status docker
      changed_when: false

  rescue:
    - name: Setup calling with a default user
      vars:
        groupname: container-data
      import_tasks: roles/common/tasks/setup-user-group.yaml

    - name: Ensure base storage is in place
      block:
        - name: Check precense of appdata
          stat:
            path: "{{ mounts.configs.ct_mountpoint }}"
          register: appdata

        - name: Perform common base setup
          import_tasks: roles/common/tasks/container-setup.yaml
          when: not appdata.stat.exists

    - name: Setup Docker in calling container
      import_tasks: roles/common/tasks/setup-docker-support.yaml

  always:
    # TODO: Contains sensitive data! Should be removed/hidden!
    # Perhaps copy to temp file, access and then remove?
    - name: Copy docker-compose.yaml
      template:
        src: docker-compose.yaml.j2
        dest: "{{ docker_compose_dir }}/docker-compose.yaml"
        owner: default-user
        group: container-data
        mode: 0644

    - name: Deploy Docker applications
      become: true
      become_user: default-user
      become_method: su
      community.docker.docker_compose:
        project_src: "{{ docker_compose_dir }}"
        state: present

    - name: Install rsync
      package:
        name: rsync
        state: latest

    - name: Ensure database directory
      file:
        path: "/home/default-user/nextcloud-database"
        state: directory

    # TODO: Check if there is an exisiting database to use first before making new copy
    # TODO: Currently broken due to permissions errors. Probably because ran by UID 999 which do not have write perm on /storage
    # - name: Ensure that databases are backed up to slower disks
    #   become: true
    #   become_user: default-user
    #   become_method: su
    #   synchronize:
    #     src: "/home/default-user/nextcloud-database"
    #     dest: /storage/appdata/nextcloud/database
    #     partial: yes

    - name: Create symlink to basic cloud data
      file:
        src: /storage/cloud
        dest: /storage/appdata/nextcloud/data/cloud
        state: link
        owner: default-user
        group: container-data

# Taken from: https://github.com/fccn/ansible-docker-deploy/blob/58f789c637fc78968a2707570327ee4db40a7198/tasks/main.yml#L283
# - name: Wait until docker health checks are healthy or ignore it if no docker healthcheck configured
#   shell: docker {% raw %} ps --format "{{.Status}}" | awk -F"[()]" '{print $2}' | awk 'NF' | sort | uniq{% endraw %}
#   register: docker_healthcheck_out
#   until: docker_healthcheck_out.stdout is not defined or docker_healthcheck_out.stdout == 'healthy' or docker_healthcheck_out.stdout == ''
#   retries: "{{ docker_deploy_healthcheck_retries | default(20) }}"
#   delay: "{{ docker_deploy_healthcheck_delay | default(omit) }}"
#   when: ( docker_deploy_shell_start is defined or docker_deploy_compose_template is defined ) and ( docker_deploy_healthcheck | default(true) )
#   changed_when: false # shell command don't change anything on the server
#   tags: docker_deploy
    
