---

# A missing sys/acl.h solved by this; https://man7.org/tlpi/code/faq.html#sys-acl.h-missing
- name: Install borg requirements
  become: true
  apt:
    pkg:
      - pip
      - pipx
      - pkg-config
      - libacl1-dev
      - libssl-dev
      - liblz4-dev
      - libzstd-dev
      - libxxhash-dev
      # Allows using systemd things for sudo users
      - dbus-user-session
      - polkitd
      # For mounting the remote backup locally
      - fuse3
      - libfuse3-dev
      - python3-pyfuse3
      - python3-llfuse

- name: Check if local bin directory is in PATH
  ansible.builtin.set_fact:
    local_bin_in_path: "{{ ansible_env.HOME ~ '/.local/bin' in ansible_env.PATH.split(':') }}"

- name: Ensure pipx installs are in path
  command: pipx --ensurepath
  changed_when: true
  when: not local_bin_in_path

- name: Install Borgmatic
  # become: true
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  loop:
    - borgmatic
    # pyfuse3 needed to enable mounting of remote repo
    - borgbackup[pyfuse3]

# If there is a system upgrade and `pyfuse3.so.4` is updated, the mounting
# might break. See https://github.com/borgbackup/borg/issues/8657#issuecomment-3146805611
# Then reinstall borg via `pipx install -f 'borgbackup[pyfuse3]' --pip-args='--no-cache-dir'`


# TODO: At some point, the /usr/local/bin/borg application was not part of the PATH,
# and as such was not found. `which borg` still replied with the above, correct path,
# but it was no longer runnable that way. Simplest fix was to just symlink it:
# ln -s /usr/local/bin/borg /usr/bin/borg

# TODO: Specify manual steps for remote repo init
# Ensure ssh pub key, e.g. via 1pass, bw. Either manually, or
# op item get "SSH Key" --fields "public key" > ~/.ssh/id_ed25519.pub
# ssh-copy-id -f -p23 -i ~/.ssh/id_ed25519.pub -s u368673@u368673.your-storagebox.de
# borgmatic init --encryption repokey --config files/cloud-borg-backup.yaml
# Enter a passphrase for the repokey encryption, manually
# borg key export ssh://u368673@u368673.your-storagebox.de:23/./cloud-backup.borg
# The passphrase alone does not suffice, but the key must also be saved
