---

- name: Borgmatic
  tags:
    - borgmatic
  vars:
    BACKUP_OP_SERVICE_ACCOUNT_TOKEN: "{{ lookup( 'onepassword', '67z7ujj5gtk6lgnzrwn72xcsva', field='credential', vault='Infrastructure' }}"
    BACKUP_OP_SSH_KEY_REFERENCE: "op://Infrastructure/wlt2nyygivk6bp7ar67zq4w6wq/private key"
  block:
    - name: Setup 1password
      import_role:
        name: 1password

    - name: Setup Borgmatic
      include_tasks:
        file: borgmatic.yaml

    - name: Setup systemd service and timer for given configuration
      loop:
        - cloud-borg-backup
      loop_control:
        loop_var: borgmatic_config_filename
      include_tasks: systemd-services.yaml
