---

- name: Check if Docker is running
  command: systemctl status docker
  ignore_errors: true
  changed_when: false
  register: service_docker_status

- debug:
    msg: "{{service_docker_status}}"

- name: Setup Docker if not present/running
  when: not service_docker_status is defined
  block:
  - name: Setup calling with a default user
    vars:
      groupname: container-data
    import_tasks: roles/common/tasks/setup-user-group.yaml

  - name: Setup Docker in calling container
    import_tasks: roles/common/tasks/setup-docker-support.yaml

- name: Copy docker-compose.yaml
  copy:
    src: docker-compose.yaml
    dest: "{{ docker_compose_dir }}"
    owner: default-user
    group: container-data
    mode: 0644

- name: Deploy docker applications
  become: true
  become_user: default-user
  become_method: su
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
    state: present

# Taken from: https://github.com/fccn/ansible-docker-deploy/blob/58f789c637fc78968a2707570327ee4db40a7198/tasks/main.yml#L283
# - name: Wait until docker health checks are healthy or ignore it if no docker healthcheck configured
#   shell: docker {% raw %} ps --format "{{.Status}}" | awk -F"[()]" '{print $2}' | awk 'NF' | sort | uniq{% endraw %}
#   register: docker_healthcheck_out
#   until: docker_healthcheck_out.stdout is not defined or docker_healthcheck_out.stdout == 'healthy' or docker_healthcheck_out.stdout == ''
#   retries: "{{ docker_deploy_healthcheck_retries | default(20) }}"
#   delay: "{{ docker_deploy_healthcheck_delay | default(omit) }}"
#   when: ( docker_deploy_shell_start is defined or docker_deploy_compose_template is defined ) and ( docker_deploy_healthcheck | default(true) )
#   changed_when: false # shell command don't change anything on the server
#   tags: docker_deploy
    
